import json
from typing import Dict, Any
import google.generativeai as genai
from config import GEMINI_API_KEY


def _init_gemini():
    """
    Initializes and returns a Gemini GenerativeModel instance.

    Raises:
        RuntimeError: If GEMINI_API_KEY is not set.

    Returns:
        genai.GenerativeModel: Gemini model instance.
    """
    if not GEMINI_API_KEY:
        raise RuntimeError("GEMINI_API_KEY is not set in environment/.env")
    genai.configure(api_key=GEMINI_API_KEY)
    return genai.GenerativeModel("gemini-2.0-flash")


def _format_summary_for_prompt(summary: Dict[str, Any]) -> str:
    """
    Formats the summary dictionary into a prompt string for Gemini.

    Args:
        summary (Dict[str, Any]): Summary dictionary with KPIs, trends, anomalies.

    Returns:
        str: Formatted prompt string.
    """
    core = summary.get("core_kpis", {})
    trend = summary.get("recent_trend", [])
    anomalies = summary.get("anomalies", [])

    trend_lines = []
    for t in trend:
        trend_lines.append(f"- {t['Date']}: revenue = {t['Revenue']:.2f}")

    anomaly_lines = []
    for a in anomalies:
        date_str = a["Date"]
        revenue = a["Revenue"]
        score = a["anomaly_score"]
        anomaly_lines.append(
            f"- {date_str}: revenue {revenue:.2f} (IsolationForest score={score:.3f})"
        )

    text = f"""
You are an expert AI Data Analyst. Your audience is a non-technical manager at a mid-size retail company who reviews this sales report weekly.
Your goal is to provide a concise, clear, and actionable business summary. Avoid technical jargon.
Base your analysis *only* on the data provided.

---
[DATA INPUT]

Core KPIs:
- Total revenue: {core.get('total_revenue', 0):.2f}
- Number of transactions: {core.get('num_transactions', 0)}
- Average order value: {core.get('avg_order_value', 0):.2f}
- Unique customers: {core.get('unique_customers', 'N/A')}
- Top country by revenue: {core.get('top_country', 'N/A')} (revenue {core.get('top_country_revenue', 0):.2f})
- Top product by revenue: {core.get('top_product', 'N/A')} (revenue {core.get('top_product_revenue', 0):.2f})

Recent weekly revenue trend:
{chr(10).join(trend_lines) if trend_lines else 'No recent trend data.'}

Detected anomalies in revenue (based on rolling z-scores):
{chr(10).join(anomaly_lines) if anomaly_lines else 'No anomalies detected.'}

[Analyst's Note on Anomalies: Isolation Forest scores are provided. A score closer to -1.0 indicates a *strong* anomaly.
Scores closer to 0 (e.g., -0.05) are *mild* deviations. Use your judgment to distinguish between minor fluctuations and business-critical issues.]

---
[TASK]

Provide your report in markdown format with the following three headings.

## Business Summary
(Start with a 1-2 sentence high-level summary of the overall business performance.)

## Key Insights (3-5 points)
(List 3-5 clear, data-driven insights. Focus on why something might be happening, not just what. Call out significant trends, top performers, or critical anomalies.)

## Recommended Actions (1-2 points)
(List 1-2 specific, concrete, and high-priority actions the retail manager should take. Recommendations must be directly based on the insights and anomalies.)
    """.strip()

    return text


def generate_insights(summary: Dict[str, Any]) -> str:
    """
    Calls Gemini to turn numeric summary into a human-readable report.

    Args:
        summary (Dict[str, Any]): Summary dictionary for analysis.

    Returns:
        str: Markdown report generated by Gemini.
    """
    model = _init_gemini()
    prompt = _format_summary_for_prompt(summary)
    response = model.generate_content(prompt)
    return response.text or ""
